name = "my-project"
type = "webpack"
account_id = "41c979ec0c01c61c270c515c9b08fc59"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
